### ISSUE TITLE
every time new activity create.

### ISSUE THREAD

**Issue by jitendra3109** [jsroyal/LoginAndRegisterWithAndroid#2]
When i go login to register and back and forth it will create a new activity again and again.

**Comment by mjurinic** [comment]
Hey, could you please describe a little more what the problem is? Is the problem that when you go back from Register to Login, and back to Register your fields in the Register form are reset?

**Comment by jitendra3109** [comment]
There is three activity login ,register and main.
 I connected them each other and when i go one to another and then back to same one that time it will be new activity created automatically.

**Comment by auracool** [comment]
is this fixed?

**Comment by jitendra3109** [comment]
Hey @jonny2plates It is fixed.
